### ISSUE TITLE
Hanging sentence in episode 05-memory

### ISSUE THREAD

**Issue by anenadic** [carpentries/instructor-training#1321] opened 2022-03-01 14:33 UTC
Episode 05-memory, [section "Attention is a Limited Resource: Cognitive Load"](https://carpentries.github.io/instructor-training/05-memory/index.html#attention-is-a-limited-resource-cognitive-load), in paragraph: 

"Adding items that demand attention adds more things to alternate between attending to, which can reduce efficiency and performance on all of them. the theory of [cognitive load](https://en.wikipedia.org/wiki/Cognitive_load). There are different theories of cognitive load, but one by Sweller posits that people have to attend to three types of things when they are learning:"

sentence "the theory of [cognitive load](https://en.wikipedia.org/wiki/Cognitive_load)." hangs and starts with a lowercase letter. Feels like there are some words missing, perhaps to connect to the previous sentence?

**Comment by anenadic** [comment] 2022-03-01 14:34
Also: "but one by Sweller posits..." -> "the but one by Sweller posits...". Feels like there should be a definite article in there.

**Comment by tobyhodges** [comment] 2022-03-02 13:21
I agree that the wording could be improved, but my suggestion would be 

> There are different theories of cognitive load. In one of these, [Sweller posits that people have to attend to three types of things when they are learning](https://doi.org/10.1207/s15516709cog1202_4):

**Comment by cknuepfer** [comment] 2022-03-03 12:47
> Episode 05-memory, [section "Attention is a Limited Resource: Cognitive Load"](https://carpentries.github.io/instructor-training/05-memory/index.html#attention-is-a-limited-resource-cognitive-load), in paragraph:
> 
> "Adding items that demand attention adds more things to alternate between attending to, which can reduce efficiency and performance on all of them. the theory of [cognitive load](https://en.wikipedia.org/wiki/Cognitive_load). There are different theories of cognitive load, but one by Sweller posits that people have to attend to three types of things when they are learning:"
> 
> sentence "the theory of [cognitive load](https://en.wikipedia.org/wiki/Cognitive_load)." hangs and starts with a lowercase letter. Feels like there are some words missing, perhaps to connect to the previous sentence?

Looks like a duplicate of #1310.

**Comment by tobyhodges** [comment] 2022-03-03 13:09
Good point @cknuepfer, regarding the hanging sentence, which I think is supposed to be a subsection heading (as you suggest in #1310).

For the other issue mentioned above - rewording the sentence about Sweller: @anenadic do you have the time & inclination to put in a PR?

**Comment by anenadic** [comment] 2022-03-04 16:31
I have done a PR #1326 to fix both this and issue #1310 @tobyhodges. Great spot on that duplicate @cknuepfer.

**Closed** 2022-03-17 22:54 UTC
Labels: pr-requested
