### ISSUE TITLE
List of lessons to teach from

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#1019] opened 2019-07-18 19:31 UTC
In the [Wrap up and Homework](https://carpentries.github.io/instructor-training/12-homework/index.html) section it lists a few SWC, LC, and DC lessons to choose from.  It says that:

> The episodes we recommend were listed in the welcome message sent to you before the start of this course,....

However the [welcome message](https://docs.carpentries.org/topic_folders/instructor_training/email_templates_admin.html#one-week-trainee-email-online-training) that trainees get says to review any of the lessons and does not make specific recommendations. Should we switch the curriculum material to not give specific recommendations or should we switch the welcome message to give specific recommendations?

**Comment by ErinBecker** [comment] 2019-07-19 16:13
Thanks for catching this @maneesha - all documentation should be updated to not make specific recommendations about which lessons to use.

**Comment by raynamharris** [comment] 2019-07-26 21:26
I think we want to leave some episodes there to help learners chose an episode (especially if they aren't very familiar with The Carpentries). Is it okay to change the wording (removing "recommended") but leave the specific examples?

**Comment by maneesha** [comment] 2019-07-29 10:43
I hadn't gotten to this since @ErinBecker  said we should not be making specific recommendations.  I also understand @raynamharris 's point about providing some guidance.   I like the idea of giving them some guidance but I'm not sure what the guidance would be based on.  If someone was most comfortable teaching a lesson other than whats [currently listed here](https://carpentries.github.io/instructor-training/12-homework/index.html) we may be doing them a disservice -- suggesting other lessons may pressure them into choosing something they are less comfortable with.

**Comment by raynamharris** [comment] 2019-07-29 16:31
There are 2 PRs open for this now (#1028 #1031 ). Both PRs say that learners can choose any episode, but the first PR also points the learners to the table of suggested demo lessons in case they need assistance. 

I'm thinking that the wording of both can be merged or there should be a group decision that no guidance should be provided.  Here's a snapshot of the proposed text. 

#1028 
Prepare for the live coding exercises. If you haven't already, pick an episode from an existing Software Carpentry, Data Carpentry, or Library Carpentry lesson and read through it carefully. Tomorrow, you will use this to practice live coding for 3 minutes in groups of three. Pick an episode from an actively maintained Software Carpentry, Data Carpentry, or Library Carpentry lesson. 
Read through the episode carefully and prepare to teach 3 minutes-worth of the material using live coding in small groups. Your group members will comment on the delivery and content.

If you need assistance choosing an episode,  we have provided [detailed table of suggested episodes](https://carpentries.github.io/instructor-training/demo_lessons/index.html) that provides of an overview of which lessons have good starting points for teaching with live coding and which episodes to avoid.


#1031 
Prepare for the live coding exercises. Visit the lesson pages for [Software Carpentry](http://software-carpentry.org/lessons/), [Data Carpentry](http://www.datacarpentry.org/lessons/), or [Library Carpentry](https://librarycarpentry.org/lessons/) and choose one episode to study in preparation for several exercises during the workshops. Familiarise yourself with the content, and prepare to teach a 5 minutes-worth of content.

**Comment by maneesha** [comment] 2020-09-08 15:28
This came up again in a recent issue posted to the Handbook repo (https://github.com/carpentries/docs.carpentries.org/issues/662).  Can we resolve this here, to note whether any lesson is OK or whether we should push trainees to a set of recommended lessons? From there we can update our documentation accordingly.

**Comment by brownsarahm** [comment] 2020-09-08 18:36
We also need to update the homework episode in addition to all the checkout places. 

We need to direct people to lessons that are on the suggested episodes list, since those have live coding. I think we should direct to that list all the time. 

https://carpentries.github.io/instructor-training/12-homework/index.html

**Comment by anenadic** [comment] 2020-09-10 12:44
At an Instructor Training yesterday there was a question if incubating lessons can be used for teaching demo at instructor checkout, but I assume the same question applies here. The question was from a person who is developing a Carpentry-style lesson in the Incubator (data carpentry for doctors). While for checkout we said that this is at the discretion of the teaching demo host and that they should be contacted in advance to check, I wonder if something should be mentioned here too? Because the purpose of the live coding exercise is to practice live teaching demonstration in front of an audience (who is not expected to be familiar with the content) and the focus is not so much on the succession of actual commands that are being taught but on the style of delivery and quality and flow of the content.

**Comment by brownsarahm** [comment] 2020-09-10 15:01
For incubator lessons, the issue is really if there is actual live coding or not, since those lessons won't be on the table for trainers.

**Comment by anenadic** [comment] 2020-09-11 08:40
Actually, it does not have to be live coding any more as long as it is a live teaching demonstration, as we have spreadsheet and OpenRefine lessons that do not contain any live coding parts.

**Comment by brownsarahm** [comment] 2020-09-11 12:26
Yes, I meant an inclusive live coding, that includes demonstration. There are several episodes that have *no* demonstration of any form and those don't work.

**Comment by karenword** [comment] 2020-09-11 17:56
I agree that pointing people at the same list for workshop prep and demo prep makes an awful lot of sense! It is something of an intimidating list, though. Maybe we could make a *very* short list, and then link out to the full demo prep list for those who want more options?

Re incubator lessons, the main reason I defer to Trainers is because they may have the familiarity with the lesson to make the call on which episodes will work, but we shouldn't assume that anyone will have this knowledge. This may create undue pressure on Trainers, though. I like the idea of letting people teach with material that appeals to them where we can, and incubator lessons may benefit from attention of this kine.

**Comment by karenword** [comment] 2022-05-31 23:31
Closing because the inconsistency cited in the original issue was resolved in our communications overhaul. There are some other lingering questions here about how we advise trainees about preparing for training and demos, but I'd like to see those raised as separate issues for future work.

**Closed by karenword** 2022-05-31 23:31 UTC
Labels: type:discussion
