### ISSUE TITLE
Old page for Checkout steps should probably be replaced

### ISSUE THREAD

**Issue by JordanPedersen** [carpentries/instructor-training#1271] opened 2021-11-04 16:49 UTC
Hey team! It looks like this page:
https://carpentries.github.io/instructor-training/14-checkout/index.html

should actually be: 
https://data-lessons.github.io/instructor-training/checkout/index.html 
because this page is not robust enough for the learners.

**Comment by JordanPedersen** [comment] 2021-11-04 16:54
This was brought up because as Jon Wheeler and I have been teaching yesterday and today (which spanned when the curriculum was merged) the old instructor notes (https://carpentries.github.io/instructor-training/etherpad/index.html) linked to the first link instead of the second. The instructor notes after the merge now refer to the second link, so it may not be an issue.
Your call!

**Comment by brownsarahm** [comment] 2021-11-04 18:28
Sorry for merging while you were teaching, we thought no one was teaching.  

I'm a little confused by your recommendation, because also nothing should refer to data-lessons anymore and the"old instructor notes" are not rendered in html anymore. 

The goal was that the [*episode*](https://carpentries.github.io/instructor-training/14-checkout/index.html) text should brief, it's the guide for the trainer on how to cover the checkout process during a workshop and the [extras/checkout](https://carpentries.github.io/instructor-training/checkout/index.html) page is detailed, it's the reference for trainees to refer to after as well. 

This is what the currently rendered materials look like they do to me. 

If you object to that delineation or think we need more text clarifying that's how the pages relate to one another, please do let us know!

**Comment by brownsarahm** [comment] 2021-12-01 22:07
I'm going to close this since everything is as intended, but @JordanPedersen please reopen if we need to fix something

**Closed** 2021-12-01 22:08 UTC
